# Generated by Django 5.2.5 on 2025-09-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Farsi')], default='en', help_text='Preferred language for the user interface', max_length=5, verbose_name='Preferred Language'),
        ),
    ]
