# Generated by Django 5.2.5 on 2025-09-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_board_name_alter_boardmembership_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmembership',
            name='invited_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
